# Generated by Django 4.2.2 on 2023-07-20 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_tweetsmodel_timestamp_tweetlike_tweetsmodel_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetsmodel',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tweets.tweetsmodel'),
        ),
    ]
